### ISSUE TITLE
Bouton de retour sur les fenêtres

### ISSUE THREAD

**Issue by OrekiFudo** [Alastrael/MaisonDesLiguesApplication#1]
Bonjour, 

Au regard de votre projet, vous êtes censé proposer une sortie de chaque fenêtre qui ne passe pas par la simple croix sur la fenêtre.
Je vous propose d'intégrer un bouton qui fermerait la fenêtre en cours avec un simple : this.Close();

Bien à vous.

**Comment by Alastrael** [comment]
Bonjour j'ai bien intégré un bouton effectuant les retours sur chaque fenêtre et un bouton quitter sur la première fenêtre.

Merci de votre conseil.
Bonne journée.
