### ISSUE TITLE
Problème pour voir les informations des usagers

### ISSUE THREAD

**Issue by OrekiFudo** [Alastrael/MaisonDesLiguesApplication#2]
Bonjour, 

Je ne trouve pas le bouton pour voir les informations des salariés. Où se trouve-t-il ?

Bonne journée et merci d'avance.

**Comment by Alastrael** [comment]
Bonjour, 

Comme indiqué dans le guide de l'utilisateur, c'est le bouton en bas à droite du menu des adhérents. N'hésitez pas à consulter le guide d'utilisateur avant de soumettre votre problème.

Cordialement.
